export const data = [
  {
    id: 10,
    path: '/dashboard',
    name: 'Dashboard',
    component: 'LAYOUT',
    redirect: '/dashboard/analysis',
    create_time: '2024-04-12 14:43:24',
    update_time: '2024-06-04 19:14:04',
    status: 1,
    permission: '/',
    title: '控制台',
    icon: 'PieChartOutlined',
    type: 0,
    sort: 100,
    parent_id: '',
    platform_id: 1,
    children: [
      {
        id: 19,
        path: '/dashboard/workbench',
        name: '工作台',
        component: '/dashboard/workbench/index',
        redirect: null,
        create_time: '2024-04-12 14:43:25',
        update_time: '2024-06-04 19:14:04',
        status: 1,
        permission: null,
        title: '工作台',
        icon: '',
        type: 0,
        sort: 0,
        parent_id: 10,
        platform_id: 1,
      },
      {
        id: 18,
        path: '/dashboard/analysis',
        name: 'Analysis',
        component: '/dashboard/analysis/index',
        redirect: null,
        create_time: '2024-04-12 14:43:25',
        update_time: '2024-06-04 19:14:04',
        status: 1,
        permission: null,
        title: '分析页',
        icon: '',
        type: 0,
        sort: 0,
        parent_id: 10,
        platform_id: 1,
      },
    ],
  },
  {
    id: 7,
    path: '/admin',
    name: '用户管理',
    component: 'LAYOUT',
    redirect: '/admin/index',
    create_time: '2024-04-12 14:43:24',
    update_time: '2024-06-04 19:14:04',
    status: 1,
    permission: null,
    title: '用户管理',
    icon: 'UserSwitchOutlined',
    type: 0,
    sort: 99,
    parent_id: '',
    platform_id: 1,
    children: [
      {
        id: 26,
        path: '/admin/group',
        name: '用户组列表',
        component: '/admin/group',
        redirect: '',
        create_time: '2024-04-25 13:11:48',
        update_time: '2024-06-04 19:14:04',
        status: 1,
        permission: null,
        title: '用户组列表',
        icon: '',
        type: 0,
        sort: 99,
        parent_id: 7,
        platform_id: 1,
      },
      {
        id: 29,
        path: '/admin/index',
        name: '用户列表',
        component: '/admin/index',
        redirect: '',
        create_time: '2024-04-25 13:14:30',
        update_time: '2024-06-04 19:14:04',
        status: 1,
        permission: null,
        title: '用户列表',
        icon: '',
        type: 0,
        sort: 1,
        parent_id: 7,
        platform_id: 1,
      },
    ],
  },
  {
    id: 8,
    path: '/company',
    name: 'company',
    component: 'LAYOUT',
    redirect: '/company/index',
    create_time: '2024-04-12 14:43:24',
    update_time: '2024-06-04 19:14:04',
    status: 1,
    permission: null,
    title: '公司管理',
    icon: 'FundProjectionScreenOutlined',
    type: 0,
    sort: 98,
    parent_id: '',
    platform_id: 1,
    children: [
      {
        id: 16,
        path: '/company/index',
        name: 'companyPage',
        component: '/company/companyList',
        redirect: null,
        create_time: '2024-04-12 14:43:24',
        update_time: '2024-06-04 19:14:04',
        status: 1,
        permission: null,
        title: '公司列表',
        icon: null,
        type: 0,
        sort: 0,
        parent_id: 8,
        platform_id: 1,
      },
    ],
  },
  {
    id: 12,
    path: '/system',
    name: 'System',
    component: 'LAYOUT',
    redirect: '/system/account',
    create_time: '2024-04-12 14:43:24',
    update_time: '2024-06-04 19:14:04',
    status: 1,
    permission: null,
    title: '系统管理',
    icon: 'SettingOutlined',
    type: 0,
    sort: 80,
    parent_id: '',
    platform_id: 1,
    children: [
      {
        id: 54,
        path: '/configuration/index',
        name: '系统配置',
        component: '/configuration/index',
        redirect: '',
        create_time: '2024-05-27 13:21:36',
        update_time: '2024-06-04 19:14:04',
        status: 1,
        permission: null,
        title: '系统配置',
        icon: '',
        type: 0,
        sort: 999,
        parent_id: 12,
        platform_id: 1,
      },
      {
        id: 22,
        path: '/system/menu/index',
        name: '菜单管理',
        component: '/system/menu/index',
        redirect: null,
        create_time: '2024-04-12 14:43:25',
        update_time: '2024-06-04 19:14:04',
        status: 1,
        permission: null,
        title: '菜单管理',
        icon: null,
        type: 0,
        sort: 99,
        parent_id: 12,
        platform_id: 1,
      },
    ],
  },
  {
    id: 78,
    path: '/demo',
    name: '',
    component: 'LAYOUT',
    redirect: '',
    create_time: '2024-08-19 11:50:21',
    update_time: '2024-08-19 11:50:21',
    status: 1,
    permission: null,
    title: '授权管理',
    icon: 'ApiFilled',
    type: 0,
    sort: 0,
    parent_id: '',
    platform_id: 1,
    children: [
      {
        id: 30,
        path: '/role/company',
        name: '公司角色管理',
        component: '/system/role/company',
        redirect: '',
        create_time: '2024-04-26 10:51:59',
        update_time: '2024-08-22 10:53:28',
        status: 1,
        permission: null,
        title: '公司角色管理',
        icon: '',
        type: 0,
        sort: 80,
        parent_id: 78,
        platform_id: 1,
      },
      {
        id: 21,
        path: '/system/role/index',
        name: '平台角色管理',
        component: '/system/role/index',
        redirect: null,
        create_time: '2024-04-12 14:43:25',
        update_time: '2024-08-22 13:15:52',
        status: 1,
        permission: null,
        title: '平台角色管理',
        icon: null,
        type: 0,
        sort: 79,
        parent_id: 78,
        platform_id: 1,
      },
      {
        id: 57,
        path: '/system/role/project',
        name: '项目角色管理',
        component: '/system/role/project',
        redirect: '',
        create_time: '2024-05-30 16:02:52',
        update_time: '2024-08-22 13:16:00',
        status: 1,
        permission: null,
        title: '项目角色管理',
        icon: '',
        type: 0,
        sort: 78,
        parent_id: 78,
        platform_id: 1,
      },
      {
        id: 71,
        path: '/system/auth/project',
        name: '项目授权管理',
        component: '/system/auth/project',
        redirect: '',
        create_time: '2024-08-08 09:39:24',
        update_time: '2024-08-22 13:16:07',
        status: 1,
        permission: null,
        title: '项目授权管理',
        icon: '',
        type: 0,
        sort: 0,
        parent_id: 78,
        platform_id: 1,
      },
      {
        id: 33,
        path: '/auth/index',
        name: '公司授权管理',
        component: '/system/auth/index',
        redirect: '',
        create_time: '2024-04-28 09:49:04',
        update_time: '2024-08-22 13:16:14',
        status: 1,
        permission: null,
        title: '公司授权管理',
        icon: '',
        type: 0,
        sort: 0,
        parent_id: 78,
        platform_id: 1,
      },
    ],
  },
  {
    id: 49,
    path: '/dictionary/index',
    name: '字典管理',
    component: 'LAYOUT',
    redirect: '',
    create_time: '2024-05-16 11:36:24',
    update_time: '2024-06-04 19:14:04',
    status: 1,
    permission: null,
    title: '字典管理',
    icon: 'DatabaseOutlined',
    type: 0,
    sort: 0,
    parent_id: '',
    platform_id: 1,
    children: [
      {
        id: 50,
        path: '/dictionary/index',
        name: '',
        component: '/dictionary/index',
        redirect: '',
        create_time: '2024-05-16 11:40:23',
        update_time: '2024-06-04 19:14:04',
        status: 1,
        permission: null,
        title: '字典表',
        icon: '',
        type: 0,
        sort: 0,
        parent_id: 49,
        platform_id: 1,
      },
    ],
  },
  {
    id: 6,
    path: '/about',
    name: 'About',
    component: 'LAYOUT',
    redirect: '/about/index',
    create_time: '2024-04-12 14:43:24',
    update_time: '2024-06-04 19:14:04',
    status: 1,
    permission: null,
    title: '关于',
    icon: 'GlobalOutlined',
    type: 0,
    sort: 0,
    parent_id: '',
    platform_id: 1,
    children: [
      {
        id: 91,
        path: '/',
        name: '测试',
        component: 'LAYOUT',
        redirect: '',
        create_time: '2024-08-22 10:05:45',
        update_time: '2024-08-22 13:17:11',
        status: 1,
        permission: null,
        title: '测试',
        icon: 'ant-design:alipay-circle-filled',
        type: 0,
        sort: 0,
        parent_id: 6,
        platform_id: 1,
      },
      {
        id: 14,
        path: '/about/index',
        name: 'AboutPage',
        component: '/sys/about/index',
        redirect: null,
        create_time: '2024-04-12 14:43:24',
        update_time: '2024-06-04 19:14:04',
        status: 1,
        permission: null,
        title: '关于',
        icon: 'simple-icons:aboutdotme',
        type: 0,
        sort: 0,
        parent_id: 6,
        platform_id: 1,
      },
    ],
  },
];
